version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret-pw
      - MYSQL_USER=sb_todo
      - MYSQL_PASSWORD=springboot-psw
      - MYSQL_DATABASE=springboot_todo
    ports:
      - 3306:3306
    networks:
      - sb-todo-net
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - sb-todo-net
    stdin_open: true
    tty: true
networks:
  sb-todo-net: