version: '2.1'
orbs:
  terraform: circleci/terraform@1.2.0
jobs:
  Build_code:
    docker:
      - image: milkamt/springboot-todo:latest
        environment:
          DATABASE_URL: $RDS_URL
          DATABASE_USER: $RDS_USER
          DATABASE_PASSWORD: $RDS_PASSWORD
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: chmod +x ./gradlew

  plan-apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .
  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file terraform.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy
workflows:
  Build:
    jobs:
      - Build_code:
          filters:
            branches:
              only:
                - main
  Deploy-Infra:
    jobs:
      - plan-apply:
          context: terraform
      - hold-apply:
          context: terraform
          type: approval
          requires:
            - plan-apply
      - apply:
          context: terraform
          requires:
            - hold-apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy