version: 2

jobs:
  build:

    docker:
      - image: milkamt/springboot-todo:latest
        environment:
          DATABASE_URL: $RDS_URL
          DATABASE_USER: $RDS_USER
          DATABASE_PASSWORD: $RDS_PASSWORD

    steps:
      - checkout
      - run: ./gradlew build