version: 2

jobs:
  build:

    docker:
      - image: milkamt/springboot-todo:latest
        environment:
          DATABASE_URL: $RDS_URL
          DATABASE_USER: $RDS_USER
          DATABASE_PASSWORD: $RDS_PASSWORD

    steps:
      - checkout
      - restore_cache:
    key: jars-{{ checksum “build.gradle” }}-{{ checksum “app/build.gradle” }}
    run:
    name: Download Dependencies
    command: ./gradlew build
               - save_cache:
    paths:
      - ~/.gradle